"""Stores common types used in the project"""


from typing import Protocol, runtime_checkable


@runtime_checkable
class Comparable(Protocol):
    """For objects which support comparison for e.g. ordering"""

    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
